<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTypeTraitValuesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('type_trait_values', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid');
            $table->unsignedBigInteger('type_id');
            $table->unsignedBigInteger('trait_id');
            $table->integer('score_min');
            $table->integer('score_max');
            $table->string('category');
            $table->timestamps();

            $table->foreign('type_id')
                ->references('id')
                ->on('professional_types');

            $table->foreign('trait_id')
                ->references('id')
                ->on('character_traits');
        });

        DB::table('type_trait_values')->insert([
            /** Физико – математический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 3,
                'score_min' => 4,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 4,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 3,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 2,
                'score_min' => 5,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 1,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'unsuitable',
            ),
            /** Химико-биологический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 4,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 2,
                'score_min' => 5,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 2,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Социально-экономический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 3,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 3,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Политический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 4,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 3,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 2,
                'score_min' => 5,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 2,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 4,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Филологический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 3,
                'score_min' => 14,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 1,
                'score_min' => 5,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 4,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 5,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Гуманитарный тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 1,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 4,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 3,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 2,
                'score_min' => 5,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 6,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Художественно-эстетический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 4,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 5,
                'score_min' => 13,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 12,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 7,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Цифровой тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 8,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Естественнонауный тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 9,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Технологический тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'unsuitable',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 10,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
            /** Оборонно-спортивный тип */
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 1,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 2,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 3,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 4,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 5,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'inherent',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 1,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 2,
                'score_min' => 9,
                'score_max' => 16,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 3,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 4,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'possible',
            ),
            array(
                'uuid' => Str::uuid(),
                'type_id' => 11,
                'trait_id' => 5,
                'score_min' => 0,
                'score_max' => 8,
                'category' => 'unsuitable',
            ),
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('type_trait_values');
    }
}
