<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class CreateLegalFormsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('legal_forms', function (Blueprint $table) {
            $table->id();
            $table->uuid('uuid');
            $table->string('title');
            $table->string('short_title')->nullable();
            $table->string('user_code')->nullable();
            $table->string('code');
            $table->timestamp('disabled_at')->nullable();
            $table->timestamps();

            $table->index('title');
            $table->index('short_title');
            $table->index('code');

            $table->unique('code');
            $table->unique('user_code');
        });

        DB::table('legal_forms')->insert([
            [
                'uuid' => Str::uuid(),
                'title' => 'Aktiengesellschaft',
                'short_title' => 'AG',
                'user_code' => 'sag',
                'code' => '62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Автономная некоммерческая организация',
                'short_title' => 'АНО',
                'user_code' => '27',
                'code' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Адвокатское бюро',
                'short_title' => 'АБ',
                'user_code' => '1025',
                'code' => '75',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'АК',
                'short_title' => 'АК',
                'user_code' => '1102',
                'code' => '60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Акционерное общество',
                'short_title' => 'АО',
                'user_code' => '7',
                'code' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Ассоциация крестьянских (фермерских) хозяйств',
                'short_title' => 'АКХ',
                'user_code' => '29',
                'code' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственная корпорация',
                'short_title' => 'ГК',
                'user_code' => '25',
                'code' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное дошкольное образовательное учреждение',
                'short_title' => 'ГБДОУ',
                'user_code' => '1014',
                'code' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное образовательное учреждение',
                'short_title' => 'ГБОУ',
                'user_code' => '1009',
                'code' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное образовательное учреждение дополнительного образования детей',
                'short_title' => 'ГБОУ ДОД',
                'user_code' => 'ГБОУ ДОД',
                'code' => '67',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное общеобразовательное учреждение',
                'short_title' => 'ГБОУ',
                'user_code' => '1013',
                'code' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное учреждение',
                'short_title' => 'ГБУ',
                'user_code' => '1008',
                'code' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное бюджетное учреждение здравоохранения',
                'short_title' => 'ГБУЗ',
                'user_code' => 'ГБУЗ',
                'code' => '69',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное казенное учреждение',
                'short_title' => 'ГКУ',
                'user_code' => '1006',
                'code' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Государственное унитарное предприятие',
                'short_title' => 'ГУП',
                'user_code' => '1010',
                'code' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Детский оздоровительный лагерь',
                'short_title' => 'ДОЛ',
                'user_code' => 'ДОЛ',
                'code' => '70',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Дочернее унитарное предприятие',
                'short_title' => 'ДУП',
                'user_code' => '13',
                'code' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Закрытое акционерное общество',
                'short_title' => 'ЗАО',
                'user_code' => '9',
                'code' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Индивидуальный предприниматель',
                'short_title' => 'ИП',
                'user_code' => '37',
                'code' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Комитет',
                'short_title' => null,
                'user_code' => '1015',
                'code' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Крестьянское (фермерское) хозяйство',
                'short_title' => 'КХ',
                'user_code' => '16',
                'code' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Министерство',
                'short_title' => null,
                'user_code' => '1022',
                'code' => '65',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Муниципальное автономное учреждение',
                'short_title' => 'МАУ',
                'user_code' => '1023',
                'code' => '73',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Муниципальное бюджетное дошкольное образовательное учреждение',
                'short_title' => 'МБДОУ',
                'user_code' => '1024',
                'code' => '74',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Муниципальное бюджетное общеобразовательное учреждение',
                'short_title' => 'МБОУ',
                'user_code' => 'МБОУ',
                'code' => '68',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Муниципальное казённое дошкольное образовательное учреждение',
                'short_title' => 'МКДОУ',
                'user_code' => 'МКДОУ',
                'code' => '66',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Муниципальное унитарное предприятие',
                'short_title' => 'МУП',
                'user_code' => '1020',
                'code' => '63',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Научно-производственное объединение',
                'short_title' => 'НПО',
                'user_code' => '1004',
                'code' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Негосударственное учреждение здравоохранения',
                'short_title' => 'НУЗ',
                'user_code' => '1017',
                'code' => '56',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Некоммерческое партнерство',
                'short_title' => 'НП',
                'user_code' => '26',
                'code' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общественная организация',
                'short_title' => 'ОО',
                'user_code' => '19',
                'code' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общественное движение',
                'short_title' => 'ОД',
                'user_code' => '20',
                'code' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общественное объединение (в том числе религиозные объединения)',
                'short_title' => 'ОО',
                'user_code' => '18',
                'code' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общество',
                'short_title' => 'О',
                'user_code' => '4',
                'code' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общество с дополнительной ответственностью',
                'short_title' => 'ОДО',
                'user_code' => '6',
                'code' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Общество с ограниченной ответственностью',
                'short_title' => 'ООО',
                'user_code' => '5',
                'code' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Объединения юридических лиц (ассоциации и союзы)',
                'short_title' => 'ОЮЛ',
                'user_code' => '28',
                'code' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Органы общественной самодеятельности',
                'short_title' => 'ООС',
                'user_code' => '21',
                'code' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Открытое акционерное общество',
                'short_title' => 'ОАО',
                'user_code' => '8',
                'code' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Отряд',
                'short_title' => 'Отряд',
                'user_code' => '1104',
                'code' => '61',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Паевые инвестиционные фонды',
                'short_title' => 'ПИФ',
                'user_code' => '34',
                'code' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Политические партии',
                'short_title' => 'ПП',
                'user_code' => '22',
                'code' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Полные товарищества',
                'short_title' => 'ПТ',
                'user_code' => '2',
                'code' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Потребительские кооперативы',
                'short_title' => 'ПК',
                'user_code' => '17',
                'code' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Представительства и филиалы',
                'short_title' => 'ПФ',
                'user_code' => '36',
                'code' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Производственное объединение',
                'short_title' => 'ПО',
                'user_code' => '1002',
                'code' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Производственные кооперативы',
                'short_title' => 'ПК',
                'user_code' => '15',
                'code' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Производственные центры',
                'short_title' => 'ПЦ',
                'user_code' => '1003',
                'code' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Простые товарищества',
                'short_title' => 'ПТ',
                'user_code' => '35',
                'code' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Прочие',
                'short_title' => 'Пр',
                'user_code' => '14',
                'code' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Публичные акционетные общества',
                'short_title' => 'ПАО',
                'user_code' => '1016',
                'code' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Садоводческие, огороднические или дачные некоммерческие товарищества',
                'short_title' => 'СОДНТ',
                'user_code' => '32',
                'code' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Санитарно-оздоровительные комплексы',
                'short_title' => 'СОК',
                'user_code' => '1019',
                'code' => '58',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Стройотдряд',
                'short_title' => 'СО',
                'user_code' => 'СО',
                'code' => '71',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Структурное подразделение',
                'short_title' => 'СП',
                'user_code' => null,
                'code' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Студенческие отряды',
                'short_title' => 'СО',
                'user_code' => '1005',
                'code' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Студенческий строительный отряд',
                'short_title' => 'ССО',
                'user_code' => 'ССО',
                'code' => '72',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Территориальные общественные самоуправления',
                'short_title' => 'ТОС',
                'user_code' => '30',
                'code' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Товарищества',
                'short_title' => 'Т',
                'user_code' => '1',
                'code' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Товарищества на вере',
                'short_title' => 'ТВ',
                'user_code' => '3',
                'code' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Товарищества собственников жилья',
                'short_title' => 'ТСЖ',
                'user_code' => '31',
                'code' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Товарищество с ограниченной ответственностью',
                'short_title' => 'ТОО',
                'user_code' => '1001',
                'code' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Унитарные предприятия',
                'short_title' => 'УП',
                'user_code' => '10',
                'code' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Унитарные предприятия, основанные на праве оперативного управления',
                'short_title' => 'УППОУ',
                'user_code' => '12',
                'code' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Унитарные предприятия, основанные на праве хозяйственного ведения',
                'short_title' => 'УППХВ',
                'user_code' => '11',
                'code' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Управление',
                'short_title' => null,
                'user_code' => '1100',
                'code' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Учреждения (в том числе общественные учреждения)',
                'short_title' => 'У',
                'user_code' => '24',
                'code' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное государственное казенное военное образовательное учреждение',
                'short_title' => 'ФГКВОУ ВО',
                'user_code' => 'ФГКВОУ',
                'code' => '77',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное бюджетное учреждение',
                'short_title' => 'ФБУ',
                'user_code' => 'ФБУ',
                'code' => '76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное государственное бюджетное образовательное учреждение высшего образования',
                'short_title' => 'ФГБОУ ВО',
                'user_code' => '1011',
                'code' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное государственное бюджетное учреждение',
                'short_title' => 'ФГБУ',
                'user_code' => '1018',
                'code' => '57',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное государственное бюджетное учреждение науки',
                'short_title' => 'ФГБУН',
                'user_code' => '1012',
                'code' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное государственное унитарное предприятие',
                'short_title' => 'ФГУП',
                'user_code' => '1101',
                'code' => '59',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Федеральное казенное учреждение',
                'short_title' => 'ФКУ',
                'user_code' => '1021',
                'code' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Филиал',
                'short_title' => 'Филиал',
                'user_code' => null,
                'code' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Финансово-промышленные группы',
                'short_title' => 'ФПГ',
                'user_code' => '33',
                'code' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'uuid' => Str::uuid(),
                'title' => 'Фонды (в том числе общественные фонды)',
                'short_title' => 'Ф',
                'user_code' => '23',
                'code' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('legal_forms');
    }
}
